### ISSUE TITLE
round corners of boxes

### ISSUE THREAD

**Issue by adeptio** [adeptio/Immerse#11]
https://www.w3schools.com/css/css3_borders.asp

**Comment by NEvans85** [comment]
This is pretty simple. borderRadius is a. acceptable attribute of the style tag. The following screenshot has a borderRadius of 0.2
<img width="847" alt="screen shot 2017-10-09 at 9 50 12 pm" src="https://user-images.githubusercontent.com/29393674/31369841-19239a92-ad3c-11e7-8221-95a88016921d.png">

**Comment by NEvans85** [comment]
https://facebook.github.io/react-vr/docs/view.html#style
Heres the part of the doc which goes over it.
